default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: battlepets_arena
  password: password1

development:
  <<: *default
  database: battlepets_arena_development

test: &test
  <<: *default
  database: battlepets_arena_test

cucumber:
  <<: *test
